/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_congwiny_jnitestdemo2_JNITestUtils */

#ifndef _Included_com_congwiny_jnitestdemo2_JNITestUtils
#define _Included_com_congwiny_jnitestdemo2_JNITestUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_congwiny_jnitestdemo2_JNITestUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_congwiny_jnitestdemo2_JNITestUtils_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
